### ISSUE TITLE
Obtrusive alert

### ISSUE THREAD

**Issue by OleVik** [hibbitts-design/grav-theme-course-hub-bones#1]
Discovered this from a [forum post](https://getgrav.org/forum#!/theme-development:pinpress-theme-issues-na) using the theme: When `built_in_css` is set to `true`, or not `false`, a JavaScript `alert` is called with the message "Please set the Use Built-in CSS option for the External Links plugin to No (i.e. False) before using this theme."

On the site in question - seemingly a base install with the theme and the External Links plugin - the alert was called three times upon a single navigation from page to page. This is very obtrusive behavior for any site, and even in testing this is very aggressive as the alert prevents all other interaction with the site. For a better user experience, may I suggest a simple `console.log` or a HTML-alert as less obstructive alternatives?

For reference, see lines 12 and 19 of [course-hub-bones.php](https://github.com/hibbitts-design/grav-theme-course-hub-bones/blob/fc247284db5f4e218120e4d419584d32f42b5604/course-hub-bones.php#L12).

**Comment by paulhibbitts** [comment]
Thanks for adding this issue, I will look into options and update the theme soon.

**Comment by paulhibbitts** [comment]
@OleVik Do you think this is a reasonable alternative?

https://github.com/hibbitts-design/grav-theme-course-hub-bones/blob/master/course-hub-bones.php#L11

https://github.com/hibbitts-design/grav-theme-course-hub-bones/blob/master/course-hub-bones.php#L11

Thanks,
Paul

**Comment by OleVik** [comment]
It definitely is unobtrusive, but would this be visible above the fold when the page loads? A more stylistic approach might be using [Foundation's Alerts](http://foundation.zurb.com/sites/docs/v/5.5.3/components/alert_boxes.html) since the theme has the CSS available for it, but that is of course your prerogative.

**Comment by paulhibbitts** [comment]
I agree, and I tried it but it did not seem to style the text maybe because of where the HTML is being called from? I will release this update for now and will further explore the lack of style rendering.

**Comment by paulhibbitts** [comment]
That's really helpful, thank very much!
